name: sbt by example

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/sbt-by-example.yml'
      - 'sbt-by-example/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/sbt-by-example.yml'
      - 'sbt-by-example/**'
  workflow_dispatch:

env:
  java_distribution: temurin
  java_version: '21'
  working_directory: ./sbt-by-example

permissions:
  contents: read

jobs:
  sbt-by-example:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: java --version
    - run: sbt --version

  sbt-by-example-compile:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: sbt-by-example
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt compile

  sbt-by-example-test:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: sbt-by-example-compile
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt test
