name: Scala CI for monorepo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  programming-in-scala:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
    - run: java --version
    - run: sbt --version

  programming-in-scala-compile:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: programming-in-scala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
    - run: sbt compile

  programming-in-scala-test:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: programming-in-scala-compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '21'
    - uses: sbt/setup-sbt@v1
    - run: sbt test
