name: Scala CI for monorepo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  java_distribution: 'temurin'
  java_version: '21'

permissions:
  contents: read

jobs:
  programming-in-scala:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    runs-on: &runner-image ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: java --version
    - run: sbt --version

  programming-in-scala-compile:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: programming-in-scala
    runs-on: *runner-image

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt compile

  programming-in-scala-test:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: programming-in-scala-compile
    runs-on: *runner-image

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt test
