name: Scala CI for monorepo

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  scala:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '11'
    - run: java --version
    - run: sbt --version
  
  scala-compile:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: scala
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '11'
    - run: sbt compile

  scala-test:
    defaults:
      run:
        working-directory: ./programming-in-scala-2015/src/scala
    needs: scala-compile
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: 'temurin'
        java-version: '11'
    - run: sbt test
    
# Optional: Upload information to the GitHub dependency graph, unblocking Dependabot alerts
#    - name: Upload dependency graph
#      uses: scalacenter/sbt-dependency-submission@ab086b50c947c9774b70f39fc7f6e20ca2706c91
