name: ScalaTest 3

on:
  pull_request:
    branches: [main]
    paths:
      - '.github/workflows/scalatest-3.yml'
      - 'scalatest-3/**'
  push:
    branches: [main]
    paths:
      - '.github/workflows/scalatest-3.yml'
      - 'scalatest-3/**'
  workflow_dispatch:

env:
  java_distribution: temurin
  java_version: '21'
  working_directory: ./scalatest-3

permissions:
  contents: read

jobs:
  scalatest-3:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: java --version
    - run: sbt --version

  scalatest-3-compile:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: scalatest-3
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt compile

  scalatest-3-test:
    defaults:
      run:
        working-directory: ${{ env.working_directory }}
    needs: scalatest-3-compile
    runs-on: ubuntu-24.04

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        cache: 'sbt'
        distribution: ${{ env.java_distribution }}
        java-version: ${{ env.java_version }}
    - uses: sbt/setup-sbt@v1
    - run: sbt test
